use crate::github::{Event, Repo, User};
use chrono::{DateTime, Datelike, Duration, NaiveDate, Utc};
use std::collections::{HashMap, HashSet};

pub fn render(user: &User, repos: &[Repo], events: &[Event], daily: &HashMap<NaiveDate, u32>, cutoff_days: i64, pr_titles: &HashMap<String, String>) -> String {
    let mut md = String::new();

    // Header
    let display_name = user.name.as_deref().unwrap_or(&user.login);
    md.push_str(&format!("# Hi, I'm {display_name} 👋\n\n"));

    if let Some(bio) = &user.bio {
        md.push_str(&format!("{bio}\n\n"));
    }

    // Badges row
    md.push_str(&badges(user));
    md.push('\n');

    // About section
    md.push_str("## About Me\n\n");
    if let Some(loc) = &user.location {
        md.push_str(&format!("- 📍 {loc}\n"));
    }
    if let Some(blog) = &user.blog {
        if !blog.is_empty() {
            md.push_str(&format!("- 🌐 [{blog}]({blog})\n"));
        }
    }
    if let Some(twitter) = &user.twitter_username {
        md.push_str(&format!(
            "- 🐦 [@{twitter}](https://twitter.com/{twitter})\n"
        ));
    }
    md.push_str(&format!(
        "- 🐙 [github.com/{}]({})\n",
        user.login, user.html_url
    ));
    md.push('\n');

    // Stats
    md.push_str("## Stats\n\n");
    md.push_str(&format!(
        "| Repos | Followers | Following |\n|-------|-----------|----------|\n| {} | {} | {} |\n\n",
        user.public_repos, user.followers, user.following
    ));

    // Commit streak
    let streak = commit_streak(daily);
    let fmt_range = |s: Option<NaiveDate>, e: Option<NaiveDate>| match (s, e) {
        (Some(s), Some(e)) if s == e => format!("{}", s.format("%b %d")),
        (Some(s), Some(e)) => format!("{} ~ {}", s.format("%b %d"), e.format("%b %d")),
        _ => String::new(),
    };
    let cur_range = fmt_range(streak.current_start, streak.current_end);
    let lng_range = fmt_range(streak.longest_start, streak.longest_end);
    md.push_str("## Commit Streak\n\n");
    md.push_str(&format!(
        "| 🔥 Current Streak | 🏆 Longest Streak |\n|-------------------|-------------------|\n| **{} days** {} | **{} days** {} |\n\n",
        streak.current, cur_range, streak.longest, lng_range
    ));
    let source = if cutoff_days > 90 {
        format!("> *Based on GitHub contribution calendar — last {cutoff_days} days*\n\n")
    } else {
        format!("> *Based on public push events — last {cutoff_days} days*\n\n")
    };
    md.push_str(&source);

    // Commit grass
    md.push_str("```\n");
    md.push_str(&commit_grass(daily));
    md.push_str("```\n\n");

    // Latest activity
    let activities = latest_activities(events, 10, pr_titles);
    if !activities.is_empty() {
        md.push_str("## Recent Activity\n\n");
        for line in &activities {
            md.push_str(&format!("- {line}\n"));
        }
        md.push('\n');
    }

    // Top repos (non-forks, sorted by stars, top 6)
    let top: Vec<&Repo> = {
        let mut v: Vec<&Repo> = repos.iter().filter(|r| !r.fork).collect();
        v.sort_by(|a, b| b.stargazers_count.cmp(&a.stargazers_count));
        v.truncate(6);
        v
    };

    if !top.is_empty() {
        md.push_str("## Top Projects\n\n");
        for repo in &top {
            let desc = repo.description.as_deref().unwrap_or("No description");
            let lang = repo
                .language
                .as_deref()
                .map(|l| format!(" `{l}`"))
                .unwrap_or_default();
            md.push_str(&format!(
                "### [{}]({}){lang}\n{desc}  \n⭐ {} · 🍴 {}\n\n",
                repo.name, repo.html_url, repo.stargazers_count, repo.forks_count
            ));
        }
    }

    // Languages bar chart
    let lang_chart = language_chart(repos);
    if !lang_chart.is_empty() {
        md.push_str("## Languages\n\n");
        md.push_str("```\n");
        md.push_str(&lang_chart);
        md.push_str("```\n\n");
    }

    md.push_str("---\n*Generated by [gh-readme-gen](https://github.com/junkpiano/gh-readme-gen)*\n");

    md
}

// ---------- streak ----------

struct Streak {
    current: u32,
    current_start: Option<NaiveDate>,
    current_end: Option<NaiveDate>,
    longest: u32,
    longest_start: Option<NaiveDate>,
    longest_end: Option<NaiveDate>,
}

fn commit_streak(daily: &HashMap<NaiveDate, u32>) -> Streak {
    let push_dates: HashSet<NaiveDate> = daily
        .iter()
        .filter(|(_, n)| **n > 0)
        .map(|(d, _)| *d)
        .collect();

    if push_dates.is_empty() {
        return Streak {
            current: 0, current_start: None, current_end: None,
            longest: 0, longest_start: None, longest_end: None,
        };
    }

    let today = Utc::now().date_naive();

    // Current streak — walk backwards from today (allow yesterday as start)
    let (current, current_start, current_end) = {
        let mut day = today;
        if !push_dates.contains(&day) {
            day -= Duration::days(1);
        }
        let end = if push_dates.contains(&day) { Some(day) } else { None };
        let mut count = 0u32;
        while push_dates.contains(&day) {
            count += 1;
            day -= Duration::days(1);
        }
        let start = if count > 0 { Some(day + Duration::days(1)) } else { None };
        (count, start, end)
    };

    // Longest streak over all available dates
    let mut sorted: Vec<NaiveDate> = push_dates.into_iter().collect();
    sorted.sort();

    let mut longest = 1u32;
    let mut longest_start = sorted.first().copied();
    let mut longest_end = sorted.first().copied();
    let mut run = 1u32;
    let mut run_start = sorted.first().copied();

    for w in sorted.windows(2) {
        if w[1] - w[0] == Duration::days(1) {
            run += 1;
            if run > longest {
                longest = run;
                longest_start = run_start;
                longest_end = Some(w[1]);
            }
        } else {
            run = 1;
            run_start = Some(w[1]);
        }
    }
    // current streak may exceed the data window
    if current > longest {
        longest = current;
        longest_start = current_start;
        longest_end = current_end;
    }

    Streak { current, current_start, current_end, longest, longest_start, longest_end }
}

// ---------- activity feed ----------

fn latest_activities(events: &[Event], limit: usize, pr_titles: &HashMap<String, String>) -> Vec<String> {
    // Dedup key: for PR/issue events include action so "opened" and "merged"
    // on the same repo both appear; for others dedup by (kind, repo).
    let mut seen = HashSet::new();
    events
        .iter()
        .filter_map(|e| {
            let action = e.payload.get("action").and_then(|v| v.as_str()).unwrap_or("");
            let key = match e.kind.as_str() {
                "PullRequestEvent" | "IssuesEvent" => {
                    format!("{}:{}:{}", e.kind, e.repo.name, action)
                }
                _ => format!("{}:{}", e.kind, e.repo.name),
            };
            if seen.contains(&key) {
                return None;
            }
            let line = describe_event(e, pr_titles)?;
            seen.insert(key);
            Some(line)
        })
        .take(limit)
        .collect()
}

fn describe_event(event: &Event, pr_titles: &HashMap<String, String>) -> Option<String> {
    let repo = &event.repo.name;
    let when = format_relative(event.created_at);
    let line = match event.kind.as_str() {
        "PushEvent" => {
            // `size` is the authoritative commit count; `commits` array may be truncated
            let n = event
                .payload
                .get("size")
                .and_then(|v| v.as_u64())
                .unwrap_or(0);
            if n == 0 {
                return None;
            }
            let msg = event
                .payload
                .get("commits")
                .and_then(|c| c.as_array())
                .and_then(|a| a.first())
                .and_then(|c| c.get("message"))
                .and_then(|m| m.as_str())
                .unwrap_or("")
                .lines()
                .next()
                .unwrap_or("")
                .trim()
                .to_string();
            if msg.is_empty() {
                format!("🔨 Pushed {n} commit(s) to `{repo}` ({when})")
            } else {
                format!("🔨 Pushed {n} commit(s) to `{repo}`: *{msg}* ({when})")
            }
        }
        "CreateEvent" => {
            let ref_type = event
                .payload
                .get("ref_type")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            if ref_type != "repository" {
                return None;
            }
            // strip "username/" prefix — the user is already known
            let short = repo.split_once('/').map(|(_, r)| r).unwrap_or(repo);
            format!("🆕 Created repository `{short}` ({when})")
        }
        "PullRequestEvent" => {
            let action = event
                .payload
                .get("action")
                .and_then(|v| v.as_str())
                .unwrap_or("updated");
            // Only surface opened/closed/merged — skip "synchronize" etc.
            if !matches!(action, "opened" | "closed" | "merged") {
                return None;
            }
            let pr = event.payload.get("pull_request");
            let number = event.payload.get("number").and_then(|v| v.as_u64()).unwrap_or(0);
            let key = format!("{}#{number}", event.repo.name);
            let title = pr_titles.get(&key).map(|s| s.as_str())
                .filter(|s| !s.is_empty())
                .unwrap_or("untitled");
            let merged = pr
                .and_then(|pr| pr.get("merged"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let url = pr
                .and_then(|pr| pr.get("html_url"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| format!("https://github.com/{repo}/pull/{number}"));
            let verb = if merged { "merged" } else { action };
            format!("🔀 {verb} PR in `{repo}`: [{title}]({url}) ({when})")
        }
        "IssuesEvent" => {
            let action = event
                .payload
                .get("action")
                .and_then(|v| v.as_str())
                .unwrap_or("updated");
            if !matches!(action, "opened" | "closed") {
                return None;
            }
            let issue = event.payload.get("issue");
            let title = issue
                .and_then(|i| i.get("title"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();
            let number = issue.and_then(|i| i.get("number")).and_then(|v| v.as_u64()).unwrap_or(0);
            let url = issue
                .and_then(|i| i.get("html_url"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| format!("https://github.com/{repo}/issues/{number}"));
            format!("🐛 {action} issue in `{repo}`: [{title}]({url}) ({when})")
        }
        "ForkEvent" => format!("🍴 Forked `{repo}` ({when})"),
        "ReleaseEvent" => {
            let tag = event
                .payload
                .get("release")
                .and_then(|r| r.get("tag_name"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();
            if tag.is_empty() {
                return None;
            }
            format!("🚀 Released `{tag}` in `{repo}` ({when})")
        }
        // WatchEvent (star) and other low-signal events are skipped
        _ => return None,
    };
    Some(line)
}

fn format_relative(dt: DateTime<Utc>) -> String {
    dt.format("%Y %b %d").to_string()
}

// ---------- commit grass ----------

fn commit_grass(daily: &HashMap<NaiveDate, u32>) -> String {
    const MONTHS: [&str; 12] = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    const DAY_LABELS: [&str; 7] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

    let today = Utc::now().date_naive();

    // Derive grid width from oldest push event (min 13, max 26 weeks)
    let oldest_push = daily.keys().min().copied();
    let weeks = match oldest_push {
        Some(d) => {
            let days = (today - d).num_days();
            ((days / 7) + 1).clamp(13, 26) as usize
        }
        None => 13,
    };

    // Align grid start to Sunday
    let days_since_sun = today.weekday().num_days_from_sunday() as i64;
    let grid_start = today - Duration::days(days_since_sun) - Duration::weeks((weeks - 1) as i64);

    // Month header: label width = 4 + 1 space = 5 chars; each cell = 2 chars
    let header_len = 5 + weeks * 2;
    let mut header: Vec<char> = vec![' '; header_len];
    let mut last_month: Option<u32> = None;
    for week in 0..weeks {
        let date = grid_start + Duration::weeks(week as i64);
        let m = date.month();
        if last_month != Some(m) {
            let label = MONTHS[(m - 1) as usize];
            let pos = 5 + week * 2;
            for (i, c) in label.chars().enumerate() {
                if pos + i < header_len {
                    header[pos + i] = c;
                }
            }
            last_month = Some(m);
        }
    }

    let mut out: String = header.into_iter().collect();
    out.push('\n');

    for dow in 0..7u32 {
        out.push_str(DAY_LABELS[dow as usize]);
        out.push_str("  ");
        for week in 0..weeks {
            let date = grid_start + Duration::days(week as i64 * 7 + dow as i64);
            let ch = if date > today {
                ' '
            } else {
                match daily.get(&date).copied().unwrap_or(0) {
                    0 => '·',
                    1..=3 => '▪',
                    4..=9 => '◼',
                    _ => '█',
                }
            };
            out.push(ch);
            out.push(' ');
        }
        out.push('\n');
    }

    out.push_str("          · 0 pushes  ▪ 1-3  ◼ 4-9  █ 10+\n");
    out
}

// ---------- helpers ----------

fn badges(user: &User) -> String {
    let login = &user.login;
    format!(
        "[![GitHub followers](https://img.shields.io/github/followers/{login}?style=social)](https://github.com/{login}) \
         [![GitHub stars](https://img.shields.io/github/stars/{login}?style=social)](https://github.com/{login})\n"
    )
}

fn language_chart(repos: &[Repo]) -> String {
    const BAR_WIDTH: usize = 24;

    let mut counts: HashMap<&str, u32> = HashMap::new();
    for repo in repos {
        if let Some(lang) = &repo.language {
            *counts.entry(lang.as_str()).or_default() += 1;
        }
    }
    let total: u32 = counts.values().sum();
    if total == 0 {
        return String::new();
    }

    let mut pairs: Vec<(&str, u32)> = counts.into_iter().collect();
    pairs.sort_by(|a, b| b.1.cmp(&a.1));
    let others: u32 = pairs.drain(10..).map(|(_, n)| n).sum();
    if others > 0 {
        pairs.push(("Others", others));
    }

    // Pad language names to the same width for alignment
    let name_width = pairs.iter().map(|(l, _)| l.len()).max().unwrap_or(0);

    let mut out = String::new();
    for (lang, n) in &pairs {
        let pct = (*n as f32 / total as f32 * 100.0).round() as usize;
        let filled = (pct * BAR_WIDTH / 100).max(if pct > 0 { 1 } else { 0 });
        let empty = BAR_WIDTH - filled;
        let bar: String = "█".repeat(filled) + &"░".repeat(empty);
        out.push_str(&format!(
            "{:<width$}  {}  {:>3}%\n",
            lang,
            bar,
            pct,
            width = name_width
        ));
    }
    out
}
