use crate::github::{Event, Repo, User};
use chrono::{DateTime, Duration, NaiveDate, Utc};
use std::collections::{HashMap, HashSet};

pub fn render(user: &User, repos: &[Repo], events: &[Event]) -> String {
    let mut md = String::new();

    // Header
    let display_name = user.name.as_deref().unwrap_or(&user.login);
    md.push_str(&format!("# Hi, I'm {display_name} 👋\n\n"));

    if let Some(bio) = &user.bio {
        md.push_str(&format!("{bio}\n\n"));
    }

    // Badges row
    md.push_str(&badges(user));
    md.push('\n');

    // About section
    md.push_str("## About Me\n\n");
    if let Some(loc) = &user.location {
        md.push_str(&format!("- 📍 {loc}\n"));
    }
    if let Some(blog) = &user.blog {
        if !blog.is_empty() {
            md.push_str(&format!("- 🌐 [{blog}]({blog})\n"));
        }
    }
    if let Some(twitter) = &user.twitter_username {
        md.push_str(&format!(
            "- 🐦 [@{twitter}](https://twitter.com/{twitter})\n"
        ));
    }
    md.push_str(&format!(
        "- 🐙 [github.com/{}]({})\n",
        user.login, user.html_url
    ));
    md.push('\n');

    // Stats
    md.push_str("## Stats\n\n");
    md.push_str(&format!(
        "| Repos | Followers | Following |\n|-------|-----------|----------|\n| {} | {} | {} |\n\n",
        user.public_repos, user.followers, user.following
    ));

    // Commit streak
    let streak = commit_streak(events);
    let fmt_range = |s: Option<NaiveDate>, e: Option<NaiveDate>| match (s, e) {
        (Some(s), Some(e)) if s == e => format!("{}", s.format("%b %d")),
        (Some(s), Some(e)) => format!("{} ~ {}", s.format("%b %d"), e.format("%b %d")),
        _ => String::new(),
    };
    let cur_range = fmt_range(streak.current_start, streak.current_end);
    let lng_range = fmt_range(streak.longest_start, streak.longest_end);
    md.push_str("## Commit Streak\n\n");
    md.push_str(&format!(
        "| 🔥 Current Streak | 🏆 Longest Streak |\n|-------------------|-------------------|\n| **{} days** {} | **{} days** {} |\n\n",
        streak.current, cur_range, streak.longest, lng_range
    ));
    md.push_str("> *Based on public push events — last 90 days*\n\n");

    // Latest activity
    let activities = latest_activities(events, 8);
    if !activities.is_empty() {
        md.push_str("## Recent Activity\n\n");
        for line in &activities {
            md.push_str(&format!("- {line}\n"));
        }
        md.push('\n');
    }

    // Top repos (non-forks, sorted by stars, top 6)
    let top: Vec<&Repo> = {
        let mut v: Vec<&Repo> = repos.iter().filter(|r| !r.fork).collect();
        v.sort_by(|a, b| b.stargazers_count.cmp(&a.stargazers_count));
        v.truncate(6);
        v
    };

    if !top.is_empty() {
        md.push_str("## Top Projects\n\n");
        for repo in &top {
            let desc = repo.description.as_deref().unwrap_or("No description");
            let lang = repo
                .language
                .as_deref()
                .map(|l| format!(" `{l}`"))
                .unwrap_or_default();
            md.push_str(&format!(
                "### [{}]({}){lang}\n{desc}  \n⭐ {} · 🍴 {}\n\n",
                repo.name, repo.html_url, repo.stargazers_count, repo.forks_count
            ));
        }
    }

    // Languages bar chart
    let lang_chart = language_chart(repos);
    if !lang_chart.is_empty() {
        md.push_str("## Languages\n\n");
        md.push_str("```\n");
        md.push_str(&lang_chart);
        md.push_str("```\n\n");
    }

    md.push_str("---\n*Generated by [gh-readme-gen](https://github.com/)*\n");

    md
}

// ---------- streak ----------

struct Streak {
    current: u32,
    current_start: Option<NaiveDate>,
    current_end: Option<NaiveDate>,
    longest: u32,
    longest_start: Option<NaiveDate>,
    longest_end: Option<NaiveDate>,
}

fn commit_streak(events: &[Event]) -> Streak {
    let push_dates: HashSet<NaiveDate> = events
        .iter()
        .filter(|e| e.kind == "PushEvent")
        .map(|e| e.created_at.date_naive())
        .collect();

    if push_dates.is_empty() {
        return Streak {
            current: 0, current_start: None, current_end: None,
            longest: 0, longest_start: None, longest_end: None,
        };
    }

    let today = Utc::now().date_naive();

    // Current streak — walk backwards from today (allow yesterday as start)
    let (current, current_start, current_end) = {
        let mut day = today;
        if !push_dates.contains(&day) {
            day -= Duration::days(1);
        }
        let end = if push_dates.contains(&day) { Some(day) } else { None };
        let mut count = 0u32;
        while push_dates.contains(&day) {
            count += 1;
            day -= Duration::days(1);
        }
        let start = if count > 0 { Some(day + Duration::days(1)) } else { None };
        (count, start, end)
    };

    // Longest streak over all available dates
    let mut sorted: Vec<NaiveDate> = push_dates.into_iter().collect();
    sorted.sort();

    let mut longest = 1u32;
    let mut longest_start = sorted.first().copied();
    let mut longest_end = sorted.first().copied();
    let mut run = 1u32;
    let mut run_start = sorted.first().copied();

    for w in sorted.windows(2) {
        if w[1] - w[0] == Duration::days(1) {
            run += 1;
            if run > longest {
                longest = run;
                longest_start = run_start;
                longest_end = Some(w[1]);
            }
        } else {
            run = 1;
            run_start = Some(w[1]);
        }
    }
    // current streak may exceed the data window
    if current > longest {
        longest = current;
        longest_start = current_start;
        longest_end = current_end;
    }

    Streak { current, current_start, current_end, longest, longest_start, longest_end }
}

// ---------- activity feed ----------

fn latest_activities(events: &[Event], limit: usize) -> Vec<String> {
    // Deduplicate: keep only the first occurrence of each (kind, repo) pair
    let mut seen = HashSet::new();
    events
        .iter()
        .filter_map(|e| {
            let key = (e.kind.clone(), e.repo.name.clone());
            if seen.contains(&key) {
                return None;
            }
            let line = describe_event(e)?;
            seen.insert(key);
            Some(line)
        })
        .take(limit)
        .collect()
}

fn describe_event(event: &Event) -> Option<String> {
    let repo = &event.repo.name;
    let when = format_relative(event.created_at);
    let line = match event.kind.as_str() {
        "PushEvent" => {
            // `size` is the authoritative commit count; `commits` array may be truncated
            let n = event
                .payload
                .get("size")
                .and_then(|v| v.as_u64())
                .unwrap_or(0);
            if n == 0 {
                return None;
            }
            let msg = event
                .payload
                .get("commits")
                .and_then(|c| c.as_array())
                .and_then(|a| a.first())
                .and_then(|c| c.get("message"))
                .and_then(|m| m.as_str())
                .unwrap_or("")
                .lines()
                .next()
                .unwrap_or("")
                .trim()
                .to_string();
            if msg.is_empty() {
                format!("🔨 Pushed {n} commit(s) to `{repo}` ({when})")
            } else {
                format!("🔨 Pushed {n} commit(s) to `{repo}`: *{msg}* ({when})")
            }
        }
        "CreateEvent" => {
            let ref_type = event
                .payload
                .get("ref_type")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            if ref_type != "repository" {
                return None;
            }
            format!("🆕 Created repository `{repo}` ({when})")
        }
        "PullRequestEvent" => {
            let action = event
                .payload
                .get("action")
                .and_then(|v| v.as_str())
                .unwrap_or("updated");
            // Only surface opened/closed/merged — skip "synchronize" etc.
            if !matches!(action, "opened" | "closed" | "merged") {
                return None;
            }
            let title = event
                .payload
                .get("pull_request")
                .and_then(|pr| pr.get("title"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();
            let merged = event
                .payload
                .get("pull_request")
                .and_then(|pr| pr.get("merged"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let verb = if merged { "merged" } else { action };
            format!("🔀 {verb} PR in `{repo}`: *{title}* ({when})")
        }
        "IssuesEvent" => {
            let action = event
                .payload
                .get("action")
                .and_then(|v| v.as_str())
                .unwrap_or("updated");
            if !matches!(action, "opened" | "closed") {
                return None;
            }
            let title = event
                .payload
                .get("issue")
                .and_then(|i| i.get("title"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();
            format!("🐛 {action} issue in `{repo}`: *{title}* ({when})")
        }
        "ForkEvent" => format!("🍴 Forked `{repo}` ({when})"),
        "ReleaseEvent" => {
            let tag = event
                .payload
                .get("release")
                .and_then(|r| r.get("tag_name"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();
            if tag.is_empty() {
                return None;
            }
            format!("🚀 Released `{tag}` in `{repo}` ({when})")
        }
        // WatchEvent (star) and other low-signal events are skipped
        _ => return None,
    };
    Some(line)
}

fn format_relative(dt: DateTime<Utc>) -> String {
    let secs = (Utc::now() - dt).num_seconds();
    match secs {
        s if s < 60 => "just now".into(),
        s if s < 3600 => format!("{}m ago", s / 60),
        s if s < 86400 => format!("{}h ago", s / 3600),
        s if s < 86400 * 30 => format!("{}d ago", s / 86400),
        s => format!("{}mo ago", s / (86400 * 30)),
    }
}

// ---------- helpers ----------

fn badges(user: &User) -> String {
    let login = &user.login;
    format!(
        "[![GitHub followers](https://img.shields.io/github/followers/{login}?style=social)](https://github.com/{login}) \
         [![GitHub stars](https://img.shields.io/github/stars/{login}?style=social)](https://github.com/{login})\n"
    )
}

fn language_chart(repos: &[Repo]) -> String {
    const BAR_WIDTH: usize = 24;

    let mut counts: HashMap<&str, u32> = HashMap::new();
    for repo in repos {
        if let Some(lang) = &repo.language {
            *counts.entry(lang.as_str()).or_default() += 1;
        }
    }
    let total: u32 = counts.values().sum();
    if total == 0 {
        return String::new();
    }

    let mut pairs: Vec<(&str, u32)> = counts.into_iter().collect();
    pairs.sort_by(|a, b| b.1.cmp(&a.1));
    let others: u32 = pairs.drain(10..).map(|(_, n)| n).sum();
    if others > 0 {
        pairs.push(("Others", others));
    }

    // Pad language names to the same width for alignment
    let name_width = pairs.iter().map(|(l, _)| l.len()).max().unwrap_or(0);

    let mut out = String::new();
    for (lang, n) in &pairs {
        let pct = (*n as f32 / total as f32 * 100.0).round() as usize;
        let filled = (pct * BAR_WIDTH / 100).max(if pct > 0 { 1 } else { 0 });
        let empty = BAR_WIDTH - filled;
        let bar: String = "█".repeat(filled) + &"░".repeat(empty);
        out.push_str(&format!(
            "{:<width$}  {}  {:>3}%\n",
            lang,
            bar,
            pct,
            width = name_width
        ));
    }
    out
}
